### PR TITLE
Fixed flag bug and also made flags show at scale

### PR DESCRIPTION
**Pull request by crc8109**
MS Zandaam will now use flag provided by API. I had to change your suggestion a little because it pulled an emoji, not a URL to the image. Please feel free to suggest a different approach if you feel it's better.

I also scaled the flags because the original size of the PNGs are huge. I made them show width at a fraction and then set height to auto to ensure that any flags outside of the typical 2:3 ratio will show accurately.

### CODE REVIEW

**Comment by colbyfayock** [comment]
sorry it took a while to comment on this. makes sense why you switched to the images since it was already available. looks like the images are bigger than the lineheight though, what about setting a fixed height and letting the width be auto instead?

image

also if you wouldn't mind removing the `console.log` and the comments :)

**Comment by crc8109** [comment]
No worries. Apologies for my delay, I've been swamped. I'll take a look this week and create a pull request when finished. Thank you for the guidance

**Comment by crc8109** [comment]
Sorry for the delay. Things have been incredibly turbulent these last few months.

Made the edits as requested. Please let me know if anything else needs tweaking.

**Comment by colbyfayock** [comment]
no worries! looks good 👍  thanks @crc8109

**Pull request merged**
